### ISSUE TITLE
Incorrect fuel level.

### ISSUE THREAD

**Issue by jszkiela72** [denpamusic/PyPlumIO#19]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I'm having the following issue:

Integration shows incorrect fuel level.
When the boiler is 100% in the lovalace I have 201%.

![obraz](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/75448769/5b70e566-2af8-4107-b788-370ef7aefd0d)

### I have following devices connected:

- [ ] ecoMAX 3xx series
- [X] ecoMAX 8xx series
- [ ] ecoMAX 9xx series
- [ ] Expansion module B
- [ ] Expansion module C
- [X] ecoSTER 200/ecoSTER Touch
- [ ] ecoLAMBDA
- [ ] ecoNET 300

### I'm connecting to my devices using:

Ethernet/WiFi to RS-485 converter

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
> Actually, on the controller I have 87% and lovelace says 188%, so I think for 101% on the controller it will be 0% in lovelace.

That's great news actually. Then we can do something like [this](https://github.com/denpamusic/PyPlumIO/commit/0f6d1d5de24ee3bc9c25ed223f953afd9bf0c344) and be done with fuel level :)

> (I went back to the stable version because I didn't have a thermostat in it.)

This is on the other hand is interesting, could you please install beta once more and provide diagnostics data from it. I don't have thermostat myself, so I can only rely on the unit tests and community to check if everything is OK.

If you have thermostat in version 0.3.x of integration, but not in 0.4.x betas, it means something with thermostat support got broken by one of many-many changes in latest PyPlumIO branch.

Thanks for your help!

**Comment by jszkiela72** [comment]
I have errors in HA. I am attaching the log for you.

[home-assistant_2023-12-07T18-12-33.426Z.log](https://github.com/denpamusic/PyPlumIO/files/13603535/home-assistant_2023-12-07T18-12-33.426Z.log)

Regards Jarek

**Comment by denpamusic** [comment]
You're welcome!
Thanks for your help with testing!
I'll take a look at schedules tomorrow, hopefully it's something simple, like with fuel level.

**Comment by jszkiela72** [comment]
Hi

Have you had time to check why the schedules are not working?

Regards, Jarek

czw., 7 gru 2023 o 21:26 Denis Paavilainen ***@***.***>
napisał(a):

**Comment by denpamusic** [comment]
Sorry, not yet.
Planed chores for module took too long :(
Don't worry I'll contact you, once I get to it. For now I've checked with my EM350P2 development stand, and EM850P2 on my boiler and it works in both cases, so unlike thermostat-related bug, it's something specific to your device.

**Comment by jszkiela72** [comment]
Hi

1. I have another boiler (Vaillant) integrated with HA in which I can set
the day and night temperatures. In your integration, I can only set the
temperature that is currently compatible with the schedule. Is there any
way to set both temperatures?

[image: obraz.png]

2. Can the integration read the opening value (%) for SM A - mixing valve -
circuit A from the controller?

[image: obraz.png]


Regards, Jarek

pon., 11 gru 2023 o 12:29 Denis Paavilainen ***@***.***>
napisał(a):

**Comment by denpamusic** [comment]
Hi,

Firstly, image attachments sadly are not process by github, so there's no point to attaching them.
Secondly, please open separate issues in the related project, this makes it far easier for other to find.
Thank you! ;)

1. Answered here: https://github.com/denpamusic/homeassistant-plum-ecomax/issues/53
2. Answered here: https://github.com/denpamusic/homeassistant-plum-ecomax/issues/54
