### ISSUE TITLE
ecoNET300

### ISSUE THREAD

**Issue by jontofront** [denpamusic/PyPlumIO#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I want to suggest:

- [X] support for a new product
- [ ] new functionality for a product
- [ ] documentation improvement
- [ ] other

### Feature description

I got with boiler with [Regulator ecoMAX800P](https://www.plum.pl/en/project/ecomax800p_en/). And I remotely connect by econect ecoNET300 remotely by web and locally by IP address. Does this library support this ecoNET300  device by TCP (I mean locally)? 

### Product page

https://www.plum.pl/en/project/econet300_en/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
PyPlumIO is ecoNET300 replacer by the design, so it will not support EN300 by itself as mentioned in https://github.com/denpamusic/homeassistant-plum-ecomax/issues/9.

However, I'm considering support for EN300 in HASS integration via separate library not related to PyPlumIO, hence all further conversation and announcement will happen in integration's issue.
