### ISSUE TITLE
ecoMax860P3-N

### ISSUE THREAD

**Issue by veldjmaxis** [denpamusic/PyPlumIO#86]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I'm having the following issue:

Hi,
My ecoMax860P-N is not working at all in pyplumio. When I connect to RS485 via WiFi I got connected but no data is available.
I try the same whit ecoanalyzer and got some data from controller.

### My environment is:

```markdown
- OS: Windows 11
- Python: 3.11
```

### I have following devices connected:

- [ ] ecoMAX 3xx series
- [X] ecoMAX 8xx series
- [ ] ecoMAX 9xx series
- [ ] Expansion module B
- [ ] Expansion module C
- [X] ecoSTER 200/ecoSTER Touch
- [ ] ecoLAMBDA
- [ ] ecoNET 300

### I'm connecting to my devices using:

Ethernet/WiFi to RS-485 converter

### I'm seeing following log messages:

```shell
Nothing.
When check via printing ecomax.data I got only connected:True.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
Hi,

Thanks for the feedback!

As you didn't provide the code, that you're trying to connect with, let's start from the very beginning, to exclude any errors related to asyncio usage.

Please download and run this script: https://gist.github.com/denpamusic/5df805524738ea1bb9c00d25ed351c46
Don't forget to change `HOST` and `PORT` variables to match your setup, and leave `DEVICE` variable as **None**.

If run is successful, this will create `ecomax_data.json` file. Please review the contents of this file with your favorite text editor and attach it to this issue.

**Comment by veldjmaxis** [comment]
Hi,
diagnostics only return timeout errors ;)
<img width="895" alt="image" src="https://github.com/denpamusic/PyPlumIO/assets/10913214/c212bd8e-5a64-4967-83be-f4a3acddcfb2">

But after some code debugging I found that there is a problem with decoding regulator data schema.
Currently there are frames with schema sent by controller but schema looks like unavailable when regulator_data tries to get it via device.get_nowait(ATTR_REGDATA_SCHEMA, []).

<img width="941" alt="image" src="https://github.com/denpamusic/PyPlumIO/assets/10913214/7317c38b-5d8c-4b30-881f-114e15a26c89">

**Comment by denpamusic** [comment]
That's interesting...

Please, try to replace [these lines](https://gist.github.com/denpamusic/5df805524738ea1bb9c00d25ed351c46#file-diagnostics-py-L81):
```python
for required in ("loaded", "regdata"):
  await ecomax.wait_for(required, timeout=TIMEOUT)
```
with
```python
await ecomax.wait_for("loaded", timeout=TIMEOUT)
```

and run diagnostics again.

**Comment by veldjmaxis** [comment]
Nope, same timeout errors.

This is odd because when I run ecoanalyzer I get some data:

<img width="761" alt="image" src="https://github.com/denpamusic/PyPlumIO/assets/10913214/75aaca93-1416-4b11-ab6e-ae0f9b6615ca">

**Comment by denpamusic** [comment]
That's really not that odd actually, since econetanalyze, uses only broadcasted RegulatorDataMessage[frame_type=0x08] frame and manually extracts all it's data (from your screenshot, not entirely correct either), but PyPlumIO mainly relies on SensorDataMessage[frame_type=0x53] which doesn't seems to be supported by your device.

Let's try some low level stuff, just to be sure, that device can respond to our requests at all.
The following script, will try to send an UID request (identification request) to the ecoMAX device and will wait infinitely for response, which should look something like on screenshot below:

![1](https://github.com/denpamusic/PyPlumIO/assets/16575433/53ded1f0-3a00-4499-a893-f5ed6d8e2140)

Don't forget to change HOST and PORT.

Please simply write does this succeed or not, you can omit posting a screenshot, as device UID can be considered sensitive information.

```python
"""Collect a single frame and dump it on screen."""

import asyncio
import sys

import pyplumio
from pyplumio.const import DeviceType
from pyplumio.frames import requests, responses

# Set host and port here.
HOST = "localhost"
PORT = 8899


async def main() -> int:
    """Collect a single UID frame and dump it on screen.

    We'll use DummyProtocol here, since we'll need direct control over
    connection and access to a raw ecoMAX frame.
    """
    async with pyplumio.open_tcp_connection(
        host=HOST, port=PORT, protocol=pyplumio.DummyProtocol()
    ) as connection:
        print("Requesting UID from the ecoMAX...")
        await connection.writer.write(requests.UIDRequest(recipient=DeviceType.ECOMAX))

        print("Waiting for response...")
        while connection.connected:
            if isinstance(
                (response := await connection.reader.read()),
                responses.UIDResponse,
            ):
                print(f"Got response ({response.length} bytes): {response}")
                break


sys.exit(asyncio.run(main()))
```

**Comment by veldjmaxis** [comment]
I just simply paste an error ;)

struct.error: unpack_from requires a buffer of at least 7 bytes for unpacking 7 bytes at offset 0 (actual buffer size is 5)

**Comment by denpamusic** [comment]
That's really weird! Does this error originates from `stream.py` module? Is it consistent (persists after running script multiple times)? Once I get home, I'll check with my device data repository collected by HASS integration users, but off the top of my head, I can confirm that I've seen at least EM850P3 work, 860 shouldn't really be that different...

**Comment by veldjmaxis** [comment]
I made some re-configuration on EW11a and finally got only one repeatable error

`stream.py", line 123, in read
    raise UnknownDeviceError(f"Unknown sender type ({sender})")
pyplumio.exceptions.UnknownDeviceError: Unknown sender type (80)`

**Comment by veldjmaxis** [comment]
I don't know why, but after powering off and on pellet controller everything seems to start working properly 👍

**Comment by denpamusic** [comment]
Thanks for the feedback, that's great to hear! 🎉

If you're using elfin EW11, I suggest increasing buffer size to at least 1024 on both **Serial Port Settings** and **Communication Settings**, as certain EM messages can reach 1000 bytes in length. I used this specific device for a long time before switching to esp32 + esphome stream server. Here's my [settings](https://github.com/denpamusic/homeassistant-plum-ecomax/issues/63#issuecomment-1884916946) just in case it breaks again (which it hopefully doesn't 😉).

**Comment by veldjmaxis** [comment]
Thanks for everything! Glad you are here doing your Best!
Wish you all the best 🎉
